[project]
name = "squant-poll-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "polars>=1.31.0",
    "pyarrow>=20.0.0",
    "setuptools>=80.9.0",
    "sweetviz>=2.3.1",
    "ydata-profiling>=4.16.1",
]
